= Ethernet Library for ESP32-CAM using HSPI interface and W5500 module =

Allow ESP32-CAM module to talk to W5500 Ethernet module trough HSPI
as SPI (VSPI) pins are used to connect the camera module
  
== Assembled from ==
* Arduino Ethernet library v2.0.0
* ESP32-CAM example "CameraWebServer"

== Licence ==
* My work - public domain / unlicence
* Their work - Whatever is copied from those two is whatever their licence is
  
== Hardware ==
* ESP32-CAM AI-Thinker module (changing the CAMERA PINS should work with any other esp32-cam, but I have not tested)
* W5500 Ethernet module (I removed the pieces for 5100 and 5200 from the library as I don't need them)
  
=== Connection ===
* GPI0 to GND and then reset to program
* GPI1 and GPI3 to your TX, RX uart for programming
* You need to disable power to the W5500 in order to program ESP32 (no idea why)
  
* ESP32-CAM  -> W5500
* GPIO12     -> MISO
* GPIO13     -> MOSI
* GPIO14     -> SCLK
* GPIO2      -> SCS
* GND        -> GND
  
I am powering both from same externam 5V source
  
Since GPIO2 is used for chip select this should not affect SD card operations as SD card is also using HSPI spi interface




Original data:

= Ethernet Library for Arduino =

With the Arduino Ethernet Shield, this library allows an Arduino board to connect to the internet.

For more information about this library please visit us at
http://www.arduino.cc/en/Reference/Ethernet

== License ==

Copyright (c) 2010 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
